/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.librerias.ImagenFondo;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.IOException;
import javax.swing.JFrame;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */
public class Inventory extends javax.swing.JFrame {
    //String UsuarioLogeado = null;
    //String rolUsuario = null;

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        try {
            initComponents();

            try {
                pnlPrincipal.setBorder(new ImagenFondo());
            } catch (IOException ex) {
                System.out.println("Ocurrio un error al inciar sistema");
            }
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            menu.setVisible(false);

            wdwIngresoDeUsuario Ingreso = new wdwIngresoDeUsuario();
            int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
            int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
            int x = (ancho / 2) - (Ingreso.getWidth() / 2);
            int y = (alto / 2) - Ingreso.getHeight();
            pnlPrincipal.add(Ingreso);
            Ingreso.setLocation(x, y);
            Ingreso.setVisible(true);
            Ingreso.toFront();
            Ingreso.setSelected(true);
        } catch (PropertyVetoException ex) {
            System.out.println("Ocurrio un error al solicitar usuario");
        }
    }
    
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("inventory/imagenes/logotipo.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pnlPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuMovimiento = new javax.swing.JMenu();
        menuCompraDeProductos = new javax.swing.JMenuItem();
        menuVentaDeProductos = new javax.swing.JMenuItem();
        menuTrasladoDeProductos = new javax.swing.JMenuItem();
        menuProforma = new javax.swing.JMenuItem();
        menuVentasActivas = new javax.swing.JMenuItem();
        menuAnulacionVentas = new javax.swing.JMenuItem();
        menuAbonoDeClientes = new javax.swing.JMenuItem();
        menuAjusteInventario = new javax.swing.JMenuItem();
        menuCatalogo = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        menuConsultaProductos = new javax.swing.JMenuItem();
        menuProveedores1 = new javax.swing.JMenuItem();
        menuSucursales = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenuItem();
        menuBonificaciones = new javax.swing.JMenuItem();
        menuContabilidad = new javax.swing.JMenu();
        menuIngresoGastos = new javax.swing.JMenuItem();
        menuSalario = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReportesAjustes = new javax.swing.JMenuItem();
        menuInventarioImpreso = new javax.swing.JMenuItem();
        menuReportesVentasPorFecha = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuReportesComprasPorFecha = new javax.swing.JMenuItem();
        menuReportesDetalleVenta = new javax.swing.JMenuItem();
        menuReportesDetalleVenta1 = new javax.swing.JMenuItem();
        menuReportesDetalleGanancia = new javax.swing.JMenuItem();
        menuReportesComisionesSucursal2 = new javax.swing.JMenuItem();
        menuReportesComisionesSucursal = new javax.swing.JMenuItem();
        menuReportesComisionesSucursal3 = new javax.swing.JMenuItem();
        menuReportesComisionesSucursal1 = new javax.swing.JMenuItem();
        menuReportesAbonosDetalle = new javax.swing.JMenuItem();
        menuReportesMovimientoProducto = new javax.swing.JMenuItem();
        menuExistenciaPorLinea = new javax.swing.JMenuItem();
        menuReportesTrasladosPorFecha = new javax.swing.JMenuItem();
        menuBaseDeDatos = new javax.swing.JMenu();
        menuExportarCatalogoDeProductos = new javax.swing.JMenuItem();
        menuImportarCatalogoDeProductos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuBaseDeDatosHistorialDeVentas = new javax.swing.JMenuItem();
        menuBaseDeDatosHistorialDeCompras = new javax.swing.JMenuItem();
        menuBaseDeDatosHistorialTraslados = new javax.swing.JMenuItem();
        menuBaseDeDatosHistorialProformas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuBaseDeDatosMantenimiento = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuManualDeUsuario = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setName("LaEconomicaInventario"); // NOI18N

        jLabel1.setText("jLabel1");

        lblUsuario.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Usuario: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Rol:");

        lblRol.setText("Rol");

        lblNombreCliente.setText("Ferrotienda La Economica & Tornisur");

        menuMovimiento.setText("Movimiento");
        menuMovimiento.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Movimiento </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Aqui se registran todos los movimientos de inventario,"
            + " como ventas, compras, cobros, etc."
            + "</td></tr> <table> </html>");

        menuCompraDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/compras.png"))); // NOI18N
        menuCompraDeProductos.setText("Compra de Productos");
        menuCompraDeProductos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Compra de Productos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Aqui se ingresan las facturas de compra para actualizar el inventario de productos. "
            + "</td></tr> <table> </html>");
        menuCompraDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompraDeProductosActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuCompraDeProductos);

        menuVentaDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/ventas.png"))); // NOI18N
        menuVentaDeProductos.setText("Venta de Productos");
        menuVentaDeProductos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Venta de Productos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Generacion de ventas al credito o contado de productos."
            + "</td></tr> <table> </html>");
        menuVentaDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentaDeProductosActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuVentaDeProductos);

        menuTrasladoDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/tralado.png"))); // NOI18N
        menuTrasladoDeProductos.setText("Traslado de Productos");
        menuTrasladoDeProductos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Venta de Productos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Generacion de ventas al credito o contado de productos."
            + "</td></tr> <table> </html>");
        menuTrasladoDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrasladoDeProductosActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuTrasladoDeProductos);

        menuProforma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/nuevo.png"))); // NOI18N
        menuProforma.setText("Crear Proforma");
        menuProforma.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Crear Proforma </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Impresion de proformas o cotizaciones."
            + "</td></tr> <table> </html>");
        menuProforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProformaActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuProforma);

        menuVentasActivas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/pantalla.png"))); // NOI18N
        menuVentasActivas.setText("Ventas Activas");
        menuVentasActivas.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Ventas Activas </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Impresion de facturas y cobros de ventas emitadas en el mostrador."
            + "</td></tr> <table> </html>");
        menuVentasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActivasActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuVentasActivas);

        menuAnulacionVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/eliminar_1.png"))); // NOI18N
        menuAnulacionVentas.setText("Anular Venta");
        menuAnulacionVentas.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Anular Venta </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Anular una venta y regresar todos los productos al inventario "
            + "</td></tr> <table> </html>");
        menuAnulacionVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnulacionVentasActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuAnulacionVentas);

        menuAbonoDeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/money.png"))); // NOI18N
        menuAbonoDeClientes.setText("Abono de Clientes");
        menuAbonoDeClientes.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Abono de Clientes </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingreso de abonos de ventas al credito a clientes."
            + "</td></tr> <table> </html>");
        menuAbonoDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbonoDeClientesActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuAbonoDeClientes);

        menuAjusteInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/ajuste_inventario.png"))); // NOI18N
        menuAjusteInventario.setText("Ajuste Inventario");
        menuAjusteInventario.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Abono de Clientes </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingreso de abonos de ventas al credito a clientes."
            + "</td></tr> <table> </html>");
        menuAjusteInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjusteInventarioActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuAjusteInventario);

        menu.add(menuMovimiento);

        menuCatalogo.setText("Catalogo");
        menuCatalogo.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Catalogo </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Informacion necesaria para el correcto "
            + "funcionamiento del sistema."
            + "</td></tr> <table> </html>");

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/clientes.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Clientes </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Registro de nuevos clientes y gestion de dias de credito."
            + "</td></tr> <table> </html>");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuClientes);

        menuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/proveedores.png"))); // NOI18N
        menuProveedores.setText("Proveedores");
        menuProveedores.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Proveedores </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Informacion de proveedores para la compra de productos."
            + "</td></tr> <table> </html>");
        menuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedoresActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuProveedores);

        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/productos.png"))); // NOI18N
        menuProductos.setText("Productos");
        menuProductos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Productos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Gestion del catalogo de productos, precios, costo, etc. "
            + "</td></tr> <table> </html>");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuProductos);

        menuConsultaProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/buscar.png"))); // NOI18N
        menuConsultaProductos.setText("Consulta");
        menuConsultaProductos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Consulta</h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Consulta de precio y existencia para los vendedores. "
            + "</td></tr> <table> </html>");
        menuConsultaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaProductosActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuConsultaProductos);

        menuProveedores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/user.png"))); // NOI18N
        menuProveedores1.setText("Usuarios");
        menuProveedores1.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Usuarios </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Creacion de usuarios para ingreso al sistema."
            + "</td></tr> <table> </html>");
        menuProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedores1ActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuProveedores1);

        menuSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        menuSucursales.setText("Sucursales");
        menuSucursales.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Sucursales </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Informacion de las distintas sucursales. "
            + "</td></tr> <table> </html>");
        menuSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSucursalesActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuSucursales);

        menuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/empleado.png"))); // NOI18N
        menuEmpleados.setText("Empleados");
        menuEmpleados.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Empleados </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Gestion de empleados, informacion y bonificaciones. "
            + "</td></tr> <table> </html>");
        menuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadosActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuEmpleados);

        menuBonificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/coins.png"))); // NOI18N
        menuBonificaciones.setText("Bonificaciones");
        menuBonificaciones.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Bonificaciones </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Creacion de bonificaciones especiales por producto"
            + "</td></tr> <table> </html>");
        menuBonificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBonificacionesActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuBonificaciones);

        menu.add(menuCatalogo);

        menuContabilidad.setText("Contabilidad");
        menuContabilidad.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Contabilidad </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingreso de cuentas varias para generacion del"
            + "estado de resultados del negocio."
            + "</td></tr> <table> </html>");

        menuIngresoGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/spending.png"))); // NOI18N
        menuIngresoGastos.setText("Ingreso de Gastos");
        menuIngresoGastos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Ingreso de Gastos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingreso de gastos administrativos por fecha y concepto para el estado de resultados. "
            + "</td></tr> <table> </html>");
        menuIngresoGastos.setActionCommand("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Ingreso de Gastos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingreso de gastos administrativos para el estado de resultados. "
            + "</td></tr> <table> </html>");
        menuContabilidad.add(menuIngresoGastos);

        menuSalario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/bank.png"))); // NOI18N
        menuSalario.setText("Ingreso de Salarios");
        menuSalario.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Ingreso de Salarios </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingreso de salarios pagados a los empleados por fecha."
            + "</td></tr> <table> </html>");
        menuSalario.setActionCommand("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Ingreso de Salarios </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingreso de salarios pagados a empleados"
            + "</td></tr> <table> </html>");
        menuContabilidad.add(menuSalario);

        menu.add(menuContabilidad);

        menuReportes.setText("Reportes");
        menuReportes.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Reportes </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Impresion de reportes varios generados"
            + " atraves del ingreso de movimientos en"
            + " el inventario."
            + "</td></tr> <table> </html>");

        menuReportesAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesAjustes.setText("Ajustes por Fecha");
        menuReportesAjustes.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Inventario Impreso </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Impresion del inventario por proveedor, "
            + "muestra las existencias el costo del "
            + "producto total segun lo registrado en el "
            + "catalogo de productos."
            + "</td></tr> <table> </html>");
        menuReportesAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesAjustesActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesAjustes);

        menuInventarioImpreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuInventarioImpreso.setText("Inventario Impreso");
        menuInventarioImpreso.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Inventario Impreso </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Impresion del inventario por proveedor, "
            + "muestra las existencias el costo del "
            + "producto total segun lo registrado en el "
            + "catalogo de productos."
            + "</td></tr> <table> </html>");
        menuInventarioImpreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInventarioImpresoActionPerformed(evt);
            }
        });
        menuReportes.add(menuInventarioImpreso);

        menuReportesVentasPorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesVentasPorFecha.setText("Ventas por Fecha");
        menuReportesVentasPorFecha.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Ventas por Fecha </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Monto total de facturas emitidas a cada cliente"
            + " ordenadas por fecha y nombre de cliente."
            + "</td></tr> <table> </html>");
        menuReportesVentasPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesVentasPorFechaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesVentasPorFecha);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        jMenuItem2.setText("Ventas por Fecha FEL");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem2);

        menuReportesComprasPorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesComprasPorFecha.setText("Compras por Fecha");
        menuReportesComprasPorFecha.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Compras por Fecha </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Monto total de facturas emitidas por proveedor, "
            + "ordenadas por fecha y nombre de proveedor."
            + "</td></tr> <table> </html>");
        menuReportesComprasPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesComprasPorFechaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesComprasPorFecha);

        menuReportesDetalleVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesDetalleVenta.setText("Detalle de Ventas por Fecha");
        menuReportesDetalleVenta.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Detalle de Ventas por Fecha </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra cada producto vendido por factura, el sub total"
            + " y el total de todas las ventas realizadas "
            + " en el rango de fecha ingresado."
            + "</td></tr> <table> </html>");
        menuReportesDetalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesDetalleVentaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesDetalleVenta);

        menuReportesDetalleVenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesDetalleVenta1.setText("Detalle de Compras por Fecha");
        menuReportesDetalleVenta1.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Detalle de Compras por Fecha </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra el total compras realizadas a cada "
            + "proveedor organizadas por nombre de proveedor "
            + " y fecha. Se detalla cada producto por numero de"
            + " factura con el su respectivo precio de compra."
            + "</td></tr> <table> </html>");
        menuReportesDetalleVenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesDetalleVenta1ActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesDetalleVenta1);

        menuReportesDetalleGanancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesDetalleGanancia.setText("Detalle de Ganancia por Fecha");
        menuReportesDetalleGanancia.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Detalle de Ganancias por Fecha </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra la cantidad total de productos vendidos"
            + " y la ganancia alcanzada por cada producto, totalizado"
            + " mediante el rango de fecha ingresado."
            + "</td></tr> <table> </html>");
        menuReportesDetalleGanancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesDetalleGananciaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesDetalleGanancia);

        menuReportesComisionesSucursal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesComisionesSucursal2.setText("Ventas por Cliente");
        menuReportesComisionesSucursal2.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Ventas por Cliente </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra el historico de ventas realizadas "
            + " a cada cliente y el estado en el que se "
            + " encuentra cada una de ellas, ordenadas por fecha."
            + "</td></tr> <table> </html>");
        menuReportesComisionesSucursal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesComisionesSucursal2ActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesComisionesSucursal2);

        menuReportesComisionesSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesComisionesSucursal.setText("Comisiones por Empleado");
        menuReportesComisionesSucursal.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Comisiones por Empleado </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Cantidad total de comisiones generadas"
            + " por cada empleado en un rango de fechas."
            + "</td></tr> <table> </html>");
        menuReportesComisionesSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesComisionesSucursalActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesComisionesSucursal);

        menuReportesComisionesSucursal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesComisionesSucursal3.setText("Comisiones sin Abonos");
        menuReportesComisionesSucursal3.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Comisiones sin Abonos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Cantidad total de comisiones generadas"
            + " por cada empleado en un rango de fechas, de"
            + " ventas al contado sin incluir abonos a"
            + " facturas pendientes de pago."
            + "</td></tr> <table> </html>");
        menuReportesComisionesSucursal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesComisionesSucursal3ActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesComisionesSucursal3);

        menuReportesComisionesSucursal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesComisionesSucursal1.setText("Comisiones por Sucursal");
        menuReportesComisionesSucursal1.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Comisiones por Sucursal </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Total de las comisiones pagadas en la sucursal."
            + "</td></tr> <table> </html>");
        menuReportesComisionesSucursal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesComisionesSucursal1ActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesComisionesSucursal1);

        menuReportesAbonosDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesAbonosDetalle.setText("Abonos por Cliente Detalle");
        menuReportesAbonosDetalle.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Abonos por Cliente Detallado </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Historial de abonos realizados por cliente."
            + "</td></tr> <table> </html>");
        menuReportesAbonosDetalle.setActionCommand("Abonos por Cliente Detale");
        menuReportesAbonosDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesAbonosDetalleActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesAbonosDetalle);

        menuReportesMovimientoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesMovimientoProducto.setText("Movimiento de Productos");
        menuReportesMovimientoProducto.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Movimiento de Productos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Cantidad comprada y vendida de productos"
            + " en un rango de fechas"
            + "</td></tr> <table> </html>");
        menuReportesMovimientoProducto.setActionCommand("Movimiento de los productos por fecha");
        menuReportesMovimientoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesMovimientoProductoActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesMovimientoProducto);

        menuExistenciaPorLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuExistenciaPorLinea.setText("Existencia por Linea");
        menuExistenciaPorLinea.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Inventario Impreso </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Impresion del inventario por proveedor, "
            + "muestra las existencias el costo del "
            + "producto total segun lo registrado en el "
            + "catalogo de productos."
            + "</td></tr> <table> </html>");
        menuExistenciaPorLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExistenciaPorLineaActionPerformed(evt);
            }
        });
        menuReportes.add(menuExistenciaPorLinea);

        menuReportesTrasladosPorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesTrasladosPorFecha.setText("Traslados por Fecha");
        menuReportesTrasladosPorFecha.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Inventario Impreso </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Impresion del inventario por proveedor, "
            + "muestra las existencias el costo del "
            + "producto total segun lo registrado en el "
            + "catalogo de productos."
            + "</td></tr> <table> </html>");
        menuReportesTrasladosPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesTrasladosPorFechaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesTrasladosPorFecha);

        menu.add(menuReportes);

        menuBaseDeDatos.setText("Base de Datos");
        menuBaseDeDatos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Base de Datos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Gestion de la informacion contnida en el sistema."
            + " Algunas opciones unicamente puede realizarlas "
            + " el desarrolador o usuario lider."
            + "</td></tr> <table> </html>");

        menuExportarCatalogoDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/exportar.png"))); // NOI18N
        menuExportarCatalogoDeProductos.setText("Exportar Catalogo de Productos");
        menuExportarCatalogoDeProductos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Exportar Catalogo de Productos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Exporta en formato CSV el catalogo de productos."
            + "</td></tr> <table> </html>");
        menuExportarCatalogoDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExportarCatalogoDeProductosActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuExportarCatalogoDeProductos);

        menuImportarCatalogoDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/importar.png"))); // NOI18N
        menuImportarCatalogoDeProductos.setText("Importar Catalogo de Productos");
        menuImportarCatalogoDeProductos.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Importar Catalogo de Productos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Importa el catalogo de productos "
            + "desde un archivo CSV."
            + "</td></tr> <table> </html>");
        menuImportarCatalogoDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportarCatalogoDeProductosActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuImportarCatalogoDeProductos);
        menuBaseDeDatos.add(jSeparator2);

        menuBaseDeDatosHistorialDeVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/historialVentas.png"))); // NOI18N
        menuBaseDeDatosHistorialDeVentas.setText("Historial de Ventas");
        menuBaseDeDatosHistorialDeVentas.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Historial de Ventas </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra el historial de ventas en un rango "
            + "de fechas y permite visualizar las facturas "
            + "o comprobante de dichas ventas."
            + "</td></tr> <table> </html>");
        menuBaseDeDatosHistorialDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBaseDeDatosHistorialDeVentasActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuBaseDeDatosHistorialDeVentas);

        menuBaseDeDatosHistorialDeCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/historialCompras.png"))); // NOI18N
        menuBaseDeDatosHistorialDeCompras.setText("Historial de Compras");
        menuBaseDeDatosHistorialDeCompras.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Historial de Compras </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra el historial de compras en un rango "
            + "de fechas y permite visualizar las facturas "
            + "o comprobante de dichas compras."
            + "</td></tr> <table> </html>");
        menuBaseDeDatosHistorialDeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBaseDeDatosHistorialDeComprasActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuBaseDeDatosHistorialDeCompras);

        menuBaseDeDatosHistorialTraslados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/historial_traslado.png"))); // NOI18N
        menuBaseDeDatosHistorialTraslados.setText("Historial de Traslados");
        menuBaseDeDatosHistorialTraslados.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Historial de Compras </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra el historial de compras en un rango "
            + "de fechas y permite visualizar las facturas "
            + "o comprobante de dichas compras."
            + "</td></tr> <table> </html>");
        menuBaseDeDatosHistorialTraslados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBaseDeDatosHistorialTrasladosActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuBaseDeDatosHistorialTraslados);

        menuBaseDeDatosHistorialProformas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/historialProformas.png"))); // NOI18N
        menuBaseDeDatosHistorialProformas.setText("Historial de Proformas");
        menuBaseDeDatosHistorialProformas.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Historial de Compras </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra el historial de compras en un rango "
            + "de fechas y permite visualizar las facturas "
            + "o comprobante de dichas compras."
            + "</td></tr> <table> </html>");
        menuBaseDeDatosHistorialProformas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBaseDeDatosHistorialProformasActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuBaseDeDatosHistorialProformas);
        menuBaseDeDatos.add(jSeparator1);

        menuBaseDeDatosMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/configurar.gif"))); // NOI18N
        menuBaseDeDatosMantenimiento.setText("Mantenimiento Base de Datos");
        menuBaseDeDatosMantenimiento.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Mantenimiento Base de Datos </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Permite gestionar toda la informacion, "
            + "contenida en la base de datos y hacer "
            + "operacion de mantenimiento."
            + "</td></tr> <table> </html>");
        menuBaseDeDatosMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBaseDeDatosMantenimientoActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuBaseDeDatosMantenimiento);

        menu.add(menuBaseDeDatos);

        menuAyuda.setText("Ayuda");
        menuAyuda.setToolTipText("");

        menuManualDeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/manual.png"))); // NOI18N
        menuManualDeUsuario.setText("Manual de Usuario");
        menuManualDeUsuario.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Manual de Usuario </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra el uso de cada opcion del sistema."
            + "</td></tr> <table> </html>");
        menuManualDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManualDeUsuarioActionPerformed(evt);
            }
        });
        menuAyuda.add(menuManualDeUsuario);

        menuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/informacion.png"))); // NOI18N
        menuAcercaDe.setText("Acerca De Inventory");
        menuAcercaDe.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Acerca de Inventory </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Muestra informacion y version del sistema actual."
            + "</td></tr> <table> </html>");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuAcercaDe);

        menu.add(menuAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPrincipal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                        .addComponent(lblNombreCliente)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRol)
                    .addComponent(lblNombreCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        
        wdwCatalogoClientes CatalogoClientes = new wdwCatalogoClientes();
        CatalogoClientes.setVisible(true);
        pnlPrincipal.add(CatalogoClientes);
        CatalogoClientes.toFront();
        
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedoresActionPerformed

        wdwCatalogoProveedores CatalogoProveedores = new wdwCatalogoProveedores();
        CatalogoProveedores.setVisible(true);
        pnlPrincipal.add(CatalogoProveedores);
        CatalogoProveedores.toFront();
    }//GEN-LAST:event_menuProveedoresActionPerformed

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed
        
        wdwCatalogoProductos CatalogoProductos = new wdwCatalogoProductos();
        CatalogoProductos.setVisible(true);
        pnlPrincipal.add(CatalogoProductos);
        CatalogoProductos.toFront();
    }//GEN-LAST:event_menuProductosActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        
        wdwAyudaAcercaDeInventario AcercaDeInventario = new wdwAyudaAcercaDeInventario();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (AcercaDeInventario.getWidth() / 2);
        int y  = (alto / 2) - (AcercaDeInventario.getHeight() / 2);
        AcercaDeInventario.setVisible(true);
        pnlPrincipal.add(AcercaDeInventario);
        AcercaDeInventario.toFront();
        AcercaDeInventario.setLocation(x, y);
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void menuCompraDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompraDeProductosActionPerformed
        wdwMovimientoCompraDeProductos CompraDeProductos = new wdwMovimientoCompraDeProductos();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (CompraDeProductos.getWidth() / 2);
        int y  = ((alto / 2) - (CompraDeProductos.getHeight() / 2)) / 2;
        CompraDeProductos.setVisible(true);
        pnlPrincipal.add(CompraDeProductos);
        CompraDeProductos.toFront();
        CompraDeProductos.setLocation(x, y);
    }//GEN-LAST:event_menuCompraDeProductosActionPerformed

    private void menuVentaDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentaDeProductosActionPerformed
        wdwMovimientoVentaDeProductos VentaDeProductos = new wdwMovimientoVentaDeProductos();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (VentaDeProductos.getWidth() / 2);
        int y  = ((alto / 2) - (VentaDeProductos.getHeight() / 2)) / 2;
        VentaDeProductos.setVisible(true);
        pnlPrincipal.add(VentaDeProductos);
        VentaDeProductos.toFront();
        VentaDeProductos.setLocation(x, y);
    }//GEN-LAST:event_menuVentaDeProductosActionPerformed

    private void menuImportarCatalogoDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportarCatalogoDeProductosActionPerformed
        
        wdwBaseDeDatosImportarCatalogoDeProductos ImportarCatalogoDeProductos = new wdwBaseDeDatosImportarCatalogoDeProductos();
        ImportarCatalogoDeProductos.setVisible(true);
        pnlPrincipal.add(ImportarCatalogoDeProductos);
        ImportarCatalogoDeProductos.toFront();
    }//GEN-LAST:event_menuImportarCatalogoDeProductosActionPerformed

    private void menuExportarCatalogoDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExportarCatalogoDeProductosActionPerformed
       
        wdwBaseDeDatosExportarCatalogoDeProductos ExportarCatalogoDeProductos = new wdwBaseDeDatosExportarCatalogoDeProductos();
        ExportarCatalogoDeProductos.setVisible(true);
        pnlPrincipal.add(ExportarCatalogoDeProductos);
        ExportarCatalogoDeProductos.toFront();
    }//GEN-LAST:event_menuExportarCatalogoDeProductosActionPerformed

    private void menuManualDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManualDeUsuarioActionPerformed
        
        wdwAyudaManualDeUsuario ManualDeUsuario = new wdwAyudaManualDeUsuario();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (ManualDeUsuario.getWidth() / 2);
        int y  = (alto / 2) - (ManualDeUsuario.getHeight() / 2);
        ManualDeUsuario.setVisible(true);
        pnlPrincipal.add(ManualDeUsuario);
        ManualDeUsuario.toFront();
        ManualDeUsuario.setLocation(x, y);
    }//GEN-LAST:event_menuManualDeUsuarioActionPerformed

    private void menuBaseDeDatosHistorialDeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBaseDeDatosHistorialDeVentasActionPerformed
        
        wdwBaseDeDAtosHistorialDeVentas HistorialDeVentas = new wdwBaseDeDAtosHistorialDeVentas();
        HistorialDeVentas.setVisible(true);
        pnlPrincipal.add(HistorialDeVentas);
        HistorialDeVentas.toFront();
    }//GEN-LAST:event_menuBaseDeDatosHistorialDeVentasActionPerformed

    private void menuBaseDeDatosHistorialDeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBaseDeDatosHistorialDeComprasActionPerformed
        
        wdwBaseDeDAtosHistorialDeCompras HistorialDeCompras = new wdwBaseDeDAtosHistorialDeCompras();
        HistorialDeCompras.setVisible(true);
        pnlPrincipal.add(HistorialDeCompras);
        HistorialDeCompras.toFront();
    }//GEN-LAST:event_menuBaseDeDatosHistorialDeComprasActionPerformed

    private void menuInventarioImpresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInventarioImpresoActionPerformed
        wdwReportesInventarioImpreso InventarioImpreso = new wdwReportesInventarioImpreso();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (InventarioImpreso.getWidth() / 2);
        int y  = (alto / 2) -  (InventarioImpreso.getHeight() / 2);
        InventarioImpreso.setLocation(x, y);
        InventarioImpreso.setVisible(true);
        pnlPrincipal.add(InventarioImpreso);
        InventarioImpreso.toFront();
    }//GEN-LAST:event_menuInventarioImpresoActionPerformed

    private void menuReportesVentasPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesVentasPorFechaActionPerformed

        wdwReportesVentasPorFecha VentasPorFecha = new wdwReportesVentasPorFecha ();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (VentasPorFecha.getWidth() / 2);
        int y  = (alto / 2) -  (VentasPorFecha.getHeight() / 2);
        VentasPorFecha.setLocation(x, y);
        VentasPorFecha .setVisible(true);
        pnlPrincipal.add(VentasPorFecha);
        VentasPorFecha .toFront();
    }//GEN-LAST:event_menuReportesVentasPorFechaActionPerformed

    private void menuProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedores1ActionPerformed
        wdwCatalogoUsuarios usuarios = new wdwCatalogoUsuarios();
        usuarios .setVisible(true);
        pnlPrincipal.add(usuarios);
        usuarios .toFront();
    }//GEN-LAST:event_menuProveedores1ActionPerformed

    private void menuSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSucursalesActionPerformed
        wdwCatalogoSucursales sucursales = new wdwCatalogoSucursales();
        sucursales .setVisible(true);
        pnlPrincipal.add(sucursales);
        sucursales .toFront();
    }//GEN-LAST:event_menuSucursalesActionPerformed

    private void menuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadosActionPerformed
        wdwCatalogoEmpleados empleado = new wdwCatalogoEmpleados();
        empleado .setVisible(true);
        pnlPrincipal.add(empleado);
        empleado .toFront();
    }//GEN-LAST:event_menuEmpleadosActionPerformed

    private void menuReportesComisionesSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesComisionesSucursalActionPerformed
        wdwReportesComisionesEmpleado reporte = new wdwReportesComisionesEmpleado();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesComisionesSucursalActionPerformed

    private void menuReportesComisionesSucursal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesComisionesSucursal1ActionPerformed
        wdwReportesComisionPorSucursal reporte = new wdwReportesComisionPorSucursal();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesComisionesSucursal1ActionPerformed

    private void menuReportesComisionesSucursal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesComisionesSucursal2ActionPerformed
        wdwReporteVentasCliente reporte = new wdwReporteVentasCliente();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesComisionesSucursal2ActionPerformed

    private void menuBonificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBonificacionesActionPerformed
        wdwCatalogoBonificacion bonificacion = new wdwCatalogoBonificacion();
        bonificacion .setVisible(true);
        pnlPrincipal.add(bonificacion);
        bonificacion .toFront();
    }//GEN-LAST:event_menuBonificacionesActionPerformed

    private void menuProformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProformaActionPerformed
        wdwMovimientoProforma proforma = new wdwMovimientoProforma();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (proforma.getWidth() / 2);
        int y  = ((alto / 2) - (proforma.getHeight() / 2)) / 2;
        proforma .setVisible(true);
        pnlPrincipal.add(proforma);
        proforma .toFront();
        proforma.setLocation(x, y);
    }//GEN-LAST:event_menuProformaActionPerformed

    private void menuVentasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActivasActionPerformed
        wdwMovimientoVentasActivas VentasActivas = new wdwMovimientoVentasActivas();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (VentasActivas.getWidth() / 2);
        int y  = ((alto / 2) - (VentasActivas.getHeight() / 2)) / 2;
        pnlPrincipal.add(VentasActivas);
        VentasActivas.setVisible(true);
        VentasActivas.toFront();
        VentasActivas.setLocation(x, y);
    }//GEN-LAST:event_menuVentasActivasActionPerformed

    private void menuAnulacionVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnulacionVentasActionPerformed
        wdwMovimientoAnulacionFacturas AnulacionDeVentas = new wdwMovimientoAnulacionFacturas();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (AnulacionDeVentas.getWidth() / 2);
        int y  = ((alto / 2) - (AnulacionDeVentas.getHeight() / 2)) / 2;
        pnlPrincipal.add(AnulacionDeVentas);
        AnulacionDeVentas.setVisible(true);
        AnulacionDeVentas.toFront();
        AnulacionDeVentas.setLocation(x, y);
    }//GEN-LAST:event_menuAnulacionVentasActionPerformed

    private void menuAbonoDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbonoDeClientesActionPerformed
        wdwAbonos AbonoClientes = new wdwAbonos();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (AbonoClientes.getWidth() / 2);
        int y  = ((alto / 2) - (AbonoClientes.getHeight() / 2)) / 2;
        pnlPrincipal.add(AbonoClientes);
        AbonoClientes.setVisible(true);
        AbonoClientes.toFront();
        AbonoClientes.setLocation(x, y);
    }//GEN-LAST:event_menuAbonoDeClientesActionPerformed

    private void menuConsultaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaProductosActionPerformed
        wdwConsultaProductos ConsultaProductos = new wdwConsultaProductos();
        ConsultaProductos.setVisible(true);
        pnlPrincipal.add(ConsultaProductos);
        ConsultaProductos.toFront();
    }//GEN-LAST:event_menuConsultaProductosActionPerformed

    private void menuReportesComisionesSucursal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesComisionesSucursal3ActionPerformed
        wdwReportesComisionesNoAbonos reporte = new wdwReportesComisionesNoAbonos();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesComisionesSucursal3ActionPerformed

    private void menuReportesAbonosDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesAbonosDetalleActionPerformed
        wdwReporteAbonosClienteDetalle reporte = new wdwReporteAbonosClienteDetalle();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesAbonosDetalleActionPerformed

    private void menuReportesDetalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesDetalleVentaActionPerformed
        wdwReporteDetalleVentasFecha reporte = new wdwReporteDetalleVentasFecha();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesDetalleVentaActionPerformed

    private void menuReportesDetalleGananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesDetalleGananciaActionPerformed
        wdwReportesDetalleGanancia reporte = new wdwReportesDetalleGanancia();        
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesDetalleGananciaActionPerformed

    private void menuReportesComprasPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesComprasPorFechaActionPerformed
        wdwReportesComprasPorFecha VentasPorFecha = new wdwReportesComprasPorFecha ();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (VentasPorFecha.getWidth() / 2);
        int y  = (alto / 2) -  (VentasPorFecha.getHeight() / 2);
        VentasPorFecha.setLocation(x, y);
        VentasPorFecha .setVisible(true);
        pnlPrincipal.add(VentasPorFecha);
        VentasPorFecha .toFront();
    }//GEN-LAST:event_menuReportesComprasPorFechaActionPerformed

    private void menuReportesDetalleVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesDetalleVenta1ActionPerformed
        wdwReporteDetalleComprasFecha reporte = new wdwReporteDetalleComprasFecha();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesDetalleVenta1ActionPerformed

    private void menuReportesMovimientoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesMovimientoProductoActionPerformed
        wdwReportesMovimientoDeProductos reporte = new wdwReportesMovimientoDeProductos();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesMovimientoProductoActionPerformed

    private void menuBaseDeDatosMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBaseDeDatosMantenimientoActionPerformed
        wdwBaseDeDatosMantenimiento Mantenimiento = new wdwBaseDeDatosMantenimiento();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (Mantenimiento.getWidth() / 2);
        int y  = ((alto / 2) - (Mantenimiento.getHeight() / 2)) / 4;
        Mantenimiento.setVisible(true);
        pnlPrincipal.add(Mantenimiento);
        Mantenimiento.toFront();
        Mantenimiento.setLocation(x, y);
    }//GEN-LAST:event_menuBaseDeDatosMantenimientoActionPerformed

    private void menuAjusteInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjusteInventarioActionPerformed
        wdwAjusteInventario AbonoClientes = new wdwAjusteInventario();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (AbonoClientes.getWidth() / 2);
        int y  = ((alto / 2) - (AbonoClientes.getHeight() / 2)) / 2;
        pnlPrincipal.add(AbonoClientes);
        AbonoClientes.setVisible(true);
        AbonoClientes.toFront();
        AbonoClientes.setLocation(x, y);
    }//GEN-LAST:event_menuAjusteInventarioActionPerformed

    private void menuExistenciaPorLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExistenciaPorLineaActionPerformed
        wdwReportesPorLinea reporte = new wdwReportesPorLinea();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuExistenciaPorLineaActionPerformed

    private void menuTrasladoDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrasladoDeProductosActionPerformed
        wdwMovimientoTrasladoDeProductos TrasladoDeProductos = new wdwMovimientoTrasladoDeProductos();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (TrasladoDeProductos.getWidth() / 2);
        int y  = ((alto / 2) - (TrasladoDeProductos.getHeight() / 2)) / 2;
        TrasladoDeProductos.setVisible(true);
        pnlPrincipal.add(TrasladoDeProductos);
        TrasladoDeProductos.toFront();
        TrasladoDeProductos.setLocation(x, y);
    }//GEN-LAST:event_menuTrasladoDeProductosActionPerformed

    private void menuBaseDeDatosHistorialTrasladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBaseDeDatosHistorialTrasladosActionPerformed
        wdwBaseDeDAtosHistorialDeTraslados HistorialDeTraslados = new wdwBaseDeDAtosHistorialDeTraslados();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (HistorialDeTraslados.getWidth() / 2);
        int y  = ((alto / 2) - (HistorialDeTraslados.getHeight() / 2)) / 2;
        HistorialDeTraslados.setVisible(true);
        pnlPrincipal.add(HistorialDeTraslados);
        HistorialDeTraslados.toFront();
        HistorialDeTraslados.setLocation(x, y);
    }//GEN-LAST:event_menuBaseDeDatosHistorialTrasladosActionPerformed

    private void menuReportesTrasladosPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesTrasladosPorFechaActionPerformed
        wdwReportesTrasladosPorFecha reporte = new wdwReportesTrasladosPorFecha();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesTrasladosPorFechaActionPerformed

    private void menuReportesAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesAjustesActionPerformed
        wdwReportesAjustes reporte = new wdwReportesAjustes();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesAjustesActionPerformed

    private void menuBaseDeDatosHistorialProformasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBaseDeDatosHistorialProformasActionPerformed
        wdwBaseDeDAtosHistorialDeProformas HistorialDeProformas = new wdwBaseDeDAtosHistorialDeProformas();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (HistorialDeProformas.getWidth() / 2);
        int y  = ((alto / 2) - (HistorialDeProformas.getHeight() / 2)) / 2;
        HistorialDeProformas.setVisible(true);
        pnlPrincipal.add(HistorialDeProformas);
        HistorialDeProformas.toFront();
        HistorialDeProformas.setLocation(x, y);
    }//GEN-LAST:event_menuBaseDeDatosHistorialProformasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        wdwReportesVentasFEL reporte = new wdwReportesVentasFEL();        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblNombreCliente;
    public static javax.swing.JLabel lblRol;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JMenuBar menu;
    public static javax.swing.JMenuItem menuAbonoDeClientes;
    private javax.swing.JMenuItem menuAcercaDe;
    public static javax.swing.JMenuItem menuAjusteInventario;
    public static javax.swing.JMenuItem menuAnulacionVentas;
    public static javax.swing.JMenu menuAyuda;
    public static javax.swing.JMenu menuBaseDeDatos;
    private javax.swing.JMenuItem menuBaseDeDatosHistorialDeCompras;
    private javax.swing.JMenuItem menuBaseDeDatosHistorialDeVentas;
    private javax.swing.JMenuItem menuBaseDeDatosHistorialProformas;
    private javax.swing.JMenuItem menuBaseDeDatosHistorialTraslados;
    public static javax.swing.JMenuItem menuBaseDeDatosMantenimiento;
    public static javax.swing.JMenuItem menuBonificaciones;
    public static javax.swing.JMenu menuCatalogo;
    public static javax.swing.JMenuItem menuClientes;
    public static javax.swing.JMenuItem menuCompraDeProductos;
    public static javax.swing.JMenuItem menuConsultaProductos;
    public static javax.swing.JMenu menuContabilidad;
    public static javax.swing.JMenuItem menuEmpleados;
    private javax.swing.JMenuItem menuExistenciaPorLinea;
    private javax.swing.JMenuItem menuExportarCatalogoDeProductos;
    private javax.swing.JMenuItem menuImportarCatalogoDeProductos;
    private javax.swing.JMenuItem menuIngresoGastos;
    private javax.swing.JMenuItem menuInventarioImpreso;
    private javax.swing.JMenuItem menuManualDeUsuario;
    public static javax.swing.JMenu menuMovimiento;
    public static javax.swing.JMenuItem menuProductos;
    public static javax.swing.JMenuItem menuProforma;
    public static javax.swing.JMenuItem menuProveedores;
    public static javax.swing.JMenuItem menuProveedores1;
    public static javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuReportesAbonosDetalle;
    private javax.swing.JMenuItem menuReportesAjustes;
    private javax.swing.JMenuItem menuReportesComisionesSucursal;
    private javax.swing.JMenuItem menuReportesComisionesSucursal1;
    private javax.swing.JMenuItem menuReportesComisionesSucursal2;
    private javax.swing.JMenuItem menuReportesComisionesSucursal3;
    private javax.swing.JMenuItem menuReportesComprasPorFecha;
    private javax.swing.JMenuItem menuReportesDetalleGanancia;
    private javax.swing.JMenuItem menuReportesDetalleVenta;
    private javax.swing.JMenuItem menuReportesDetalleVenta1;
    private javax.swing.JMenuItem menuReportesMovimientoProducto;
    private javax.swing.JMenuItem menuReportesTrasladosPorFecha;
    private javax.swing.JMenuItem menuReportesVentasPorFecha;
    private javax.swing.JMenuItem menuSalario;
    public static javax.swing.JMenuItem menuSucursales;
    public static javax.swing.JMenuItem menuTrasladoDeProductos;
    public static javax.swing.JMenuItem menuVentaDeProductos;
    public static javax.swing.JMenuItem menuVentasActivas;
    public static javax.swing.JDesktopPane pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
