/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoBonificacion;
import inventory.acceso.AccesoExcepciones;
import inventory.objetos.ObjetosBonificacion;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class wdwCatalogoBonificacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form wdwIngresoClientes
     */
    public wdwCatalogoBonificacion() {
        initComponents();
        mostrarRegistrosGuardados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblIdBonificacion = new javax.swing.JLabel();
        txtIdBonificacion = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        lblPorcentaje = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox();
        pnlBotones = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBonificacion = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Bonificaciones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/clientes.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        pnlEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIdBonificacion.setText("ID Bonificacion");

        txtIdBonificacion.setBackground(new java.awt.Color(102, 102, 102));
        txtIdBonificacion.setEditable(false);
        txtIdBonificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtIdBonificacion.setToolTipText("Este campo no se puede editar el programa asigana automaticamente un numero de ID");

        lblDescripcion.setText("Descripcion");

        lblEstado.setText("Estado");

        lblCantidad.setText("Cantidad");

        txtCantidad.setToolTipText("Ingrese una cantidad de bonificacion");

        txtDescripcion.setToolTipText("Ingrese el nombre de esta bonificacion");
        txtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusGained(evt);
            }
        });

        lblPorcentaje.setText("Porcentaje");

        txtPorcentaje.setToolTipText("Ingrese el porcentaje de la bonificacion");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activa", "Cancelada" }));
        cbxEstado.setToolTipText("");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado)
                    .addComponent(lblIdBonificacion)
                    .addComponent(lblPorcentaje))
                .addGap(0, 18, 18)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdBonificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(txtCantidad))
                .addContainerGap())
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdBonificacion)
                    .addComponent(txtIdBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentaje)
                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setText("Buscar");

        txtBuscar.setToolTipText("Ingrese la descripcion de la bonificacion a buscar");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBuscar)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir)
                        .addComponent(btnLimpiar)
                        .addComponent(btnModificar)
                        .addComponent(btnGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblBonificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBonificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBonificacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBonificacion);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //VARIABLES GLOBALES
    AccesoExcepciones Mensaje = new AccesoExcepciones();
    AccesoBonificacion NuevaBonificacion = new AccesoBonificacion();
    ObjetosBonificacion Bonificacion = new ObjetosBonificacion();
    boolean bonificacion_encontrado = false;

    private void limpiarCampos() {
        
        btnGuardar.setEnabled(true);
        
        txtIdBonificacion.setText("");
        txtDescripcion.setText("");
        cbxEstado.setSelectedItem("Activa");
        txtCantidad.setText("");
        txtPorcentaje.setText("");

        bonificacion_encontrado = false;
    }

    private void mostrarRegistrosGuardados() {

        DefaultTableModel tabla = new DefaultTableModel();

        ArrayList<ObjetosBonificacion> listaBonificaciones = new ArrayList();

        //VERIFICAR ALGUN ERROR AL CARGAR LA INFORMACION DE LOS CLIENTES
        try {
            listaBonificaciones = NuevaBonificacion.seleccionarBonificacion();
            System.out.println("SE CONSULTARON LOS DATOS DE BONIFICACIONES");
        } catch (Error error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consultar la informacion -> " + error);
        }

        //MOSTRAR LA INFORMACION DE LOS CLIENTES EN LA TABLA DE LA VISTA
        if (listaBonificaciones.isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "No existen datos almacenados de bonificaciones");
        } else {
            tabla.addColumn("Descripcion");
            tabla.addColumn("Estado");
            tabla.addColumn("cantidad");
            tabla.addColumn("Porcentaje");
            tabla.setRowCount(listaBonificaciones.size());
            int cCliente = 0;

            for (ObjetosBonificacion xBonif : listaBonificaciones) {
                        tabla.setValueAt(xBonif.getDescripcion_bonificacion(), cCliente, 0);
                        tabla.setValueAt(xBonif.getEstado_bonificacion(), cCliente, 1);
                        tabla.setValueAt(xBonif.getCantidad_bonificacion(), cCliente, 2);
                        tabla.setValueAt(xBonif.getPorcentaje_bonificacion(), cCliente, 3);
                        System.out.println("SE CONSULTO CON EXITO EL ID: " + xBonif.getId_bonificacion());
                   
                cCliente++;
            }

            tblBonificacion.setModel(tabla);
        }
    }

    private int obtenerIdBonificacion(String pDescripcion) {

        int id = 0;
        ArrayList<ObjetosBonificacion> BuscarBonificacion = new ArrayList();

        try {
            BuscarBonificacion = NuevaBonificacion.buscarBonificacion(pDescripcion);
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consulta el ID de la bonificacion -> " + error);
        }

        if (BuscarBonificacion.isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "No existe esta bonificacion en la Base de Datos");
        } else {
            id = BuscarBonificacion.get(0).getId_bonificacion();
        }

        return id;
    }

    private void buscarEnRegistrosGuardados() {

        String busqueda = txtBuscar.getText();

        if (busqueda != null) {
            DefaultTableModel tabla = new DefaultTableModel();
            ArrayList<ObjetosBonificacion> listaBonificaciones = new ArrayList();

            //VERIFICAR ALGUN ERROR AL CARGAR LA INFORMACION DE LOS CLIENTES
            try {
                listaBonificaciones = NuevaBonificacion.seleccionarBonificacion();
                System.out.println("SE CONSULTARON LOS DATOS DE BONIFICACIONES");
            } catch (Error error) {
                Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consultar la informacion -> " + error);
            }

            //MOSTRAR LA INFORMACION DE LOS CLIENTES EN LA TABLA DE LA VISTA
            if (listaBonificaciones.isEmpty()) {
                Mensaje.manipulacionExcepciones("critico", "No existen datos almacenados de bonificaciones");
            } else {
                tabla.addColumn("Descripcion");
                tabla.addColumn("Estado");
                tabla.addColumn("Cantidad");
                tabla.addColumn("Porcentaje");

                int cCliente = 0;
                int contadorFilas = 1;

                // RECORRO TODA LA LISTA DE PERSONAS
                for (ObjetosBonificacion xBonif : listaBonificaciones) {

                    // COMPARA CADA ELEMENTO NIT Y NOMBRE DE LA LISTA PARA VER SI ALGUNO ES EL BUSCADO
                    if (xBonif.getDescripcion_bonificacion().indexOf(busqueda) >= 0) {


                                // ESTABLECE EL TAMAÑO DE LA TABLA
                                tabla.setRowCount(contadorFilas);

                                tabla.setValueAt(xBonif.getDescripcion_bonificacion(), cCliente, 0);
                                tabla.setValueAt(xBonif.getEstado_bonificacion(), cCliente, 1);
                                tabla.setValueAt(xBonif.getCantidad_bonificacion(), cCliente, 2);
                                tabla.setValueAt(xBonif.getPorcentaje_bonificacion(), cCliente, 3);

                                System.out.println("SE ENCONTRO EL REGISTRO BUSCADO: " + xBonif.getDescripcion_bonificacion());

                                cCliente++;
                                contadorFilas++;

                    }
                }
                tblBonificacion.setModel(tabla);
            }
        } else {
            // SI NO HAY CARACTER DE BUSQUEDA SE DESPLIEGAN TODOS LOS DATOS
            mostrarRegistrosGuardados();
        }

    }

    

    private boolean verificarDatos() {

        boolean vDatosCorrectos = true;

        if (txtDescripcion.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el Nombre del cliente");
            vDatosCorrectos = false;
        }
        if (txtCantidad.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese la Direccion del cliente");
            vDatosCorrectos = false;
        }
        if(txtPorcentaje.getText().isEmpty()){
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de celular");
        }
        
        return vDatosCorrectos;
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed


        if (verificarDatos()) {
            Bonificacion.setId_bonificacion(0);
            Bonificacion.setDescripcion_bonificacion(txtDescripcion.getText());
            Bonificacion.setCantidad_bonificacion(Float.parseFloat(txtCantidad.getText()));
            Bonificacion.setEstado_bonificacion(cbxEstado.getSelectedItem().toString());
            Bonificacion.setPorcentaje_bonificacion(Float.parseFloat(txtPorcentaje.getText()));
        
            try {
                NuevaBonificacion.insertarBonificacion(Bonificacion);
                limpiarCampos();
                buscarEnRegistrosGuardados();
            } catch (Exception error) {
                Mensaje.manipulacionExcepciones("critico", "Ocurrio un erro al guardar la bonificacion -> " + error);
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        Mensaje.manipulacionExcepciones("interrogante", "¿Esta seguro que desea salir?");
        if (Mensaje.valor == 0) {
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarEnRegistrosGuardados();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        //ACTUALIZAR LOS DATOS DE PERSONA
        Bonificacion.setId_bonificacion(Integer.parseInt(txtIdBonificacion.getText()));
        Bonificacion.setDescripcion_bonificacion(txtDescripcion.getText());
        Bonificacion.setCantidad_bonificacion(Float.parseFloat(txtCantidad.getText()));
        Bonificacion.setEstado_bonificacion(cbxEstado.getSelectedItem().toString());
        Bonificacion.setPorcentaje_bonificacion(Float.parseFloat(txtPorcentaje.getText()));
       
        try {
            Mensaje.manipulacionExcepciones("informacion", NuevaBonificacion.actualizarBonificacion(Bonificacion));
            limpiarCampos();
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al actualizar bonificacion -> " + error);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblBonificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBonificacionMouseClicked
        
        btnGuardar.setEnabled(false);
        if (String.valueOf(tblBonificacion.getSelectedColumn()).equals("0")) {
            int fila_seleccionada = tblBonificacion.getSelectedRow();
            int columna_seleccionada = tblBonificacion.getSelectedColumn();
            
            txtDescripcion.setText(String.valueOf(tblBonificacion.getValueAt(fila_seleccionada, columna_seleccionada)));
            cbxEstado.setSelectedItem(String.valueOf(tblBonificacion.getValueAt(fila_seleccionada, columna_seleccionada + 1)));
            txtCantidad.setText(String.valueOf(tblBonificacion.getValueAt(fila_seleccionada, columna_seleccionada + 2)));
            txtPorcentaje.setText(String.valueOf(tblBonificacion.getValueAt(fila_seleccionada, columna_seleccionada + 3)));
           
            //YA SELECCIONADO EL NIT BUSCO EL CLIENTE CON EL METODO BUSCAR ID CLIENTE
            txtIdBonificacion.setText(String.valueOf(obtenerIdBonificacion(txtDescripcion.getText())));
        }
    }//GEN-LAST:event_tblBonificacionMouseClicked

    private void txtDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusGained
/*
        if (txtDescripcion.getText().isEmpty()) {
            txtDescripcion.requestFocus();
            Mensaje.manipulacionExcepciones("critico", "Ingrese una descripcion de la bonificacion");
        }*/
    }//GEN-LAST:event_txtDescripcionFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdBonificacion;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JTable tblBonificacion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdBonificacion;
    private javax.swing.JTextField txtPorcentaje;
    // End of variables declaration//GEN-END:variables
}
