/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoCliente;
import inventory.acceso.AccesoExcepciones;
import inventory.acceso.AccesoPersona;
import inventory.objetos.ObjetosCliente;
import inventory.objetos.ObjetosPersona;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class wdwCatalogoClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form wdwIngresoClientes
     */
    public wdwCatalogoClientes() {
        initComponents();
        mostrarRegistrosGuardados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblIdCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        lblNitCliente = new javax.swing.JLabel();
        txtNitPersona = new javax.swing.JTextField();
        lblTelCliente = new javax.swing.JLabel();
        txtTelCliente = new javax.swing.JTextField();
        lblDirCliente = new javax.swing.JLabel();
        txtDirCliente = new javax.swing.JTextField();
        txtNomPersona = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblIdPersona = new javax.swing.JLabel();
        txtIdPersona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLimiteCredito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipoCliente = new javax.swing.JTextField();
        cbxDiasCredito = new javax.swing.JComboBox();
        pnlBotones = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/clientes.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        pnlEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIdCliente.setText("ID Cliente");

        txtIdCliente.setBackground(new java.awt.Color(102, 102, 102));
        txtIdCliente.setEditable(false);
        txtIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCliente.setToolTipText("Este campo no se puede editar el programa asigana automaticamente un numero de ID");

        lblNombreCliente.setText("Nombre");

        lblNitCliente.setText("NIT o DPI");

        txtNitPersona.setToolTipText("Ingrese el numero de NIT");
        txtNitPersona.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNitPersonaFocusLost(evt);
            }
        });

        lblTelCliente.setText("Telefono");

        txtTelCliente.setToolTipText("Ingrese el numero de Telefono sin guiones");

        lblDirCliente.setText("Direccion");

        txtDirCliente.setToolTipText("Ingrese la direccion tien un espacio maximo de 200 caracteres");

        txtNomPersona.setToolTipText("Ingrese el nombre completo del cliente este nombre no puede contener simbolos ni numeros");
        txtNomPersona.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomPersonaFocusGained(evt);
            }
        });

        lblCelular.setText("Celular");

        txtCelular.setToolTipText("Ingrese el numero de Telefono sin guiones");

        lblEmail.setText("Email");

        txtEmail.setToolTipText("Ingrese la direccion tien un espacio maximo de 200 caracteres");

        lblIdPersona.setText("Persona");

        txtIdPersona.setBackground(new java.awt.Color(102, 102, 102));
        txtIdPersona.setEditable(false);
        txtIdPersona.setForeground(new java.awt.Color(255, 255, 255));
        txtIdPersona.setToolTipText("Este campo no se puede editar el programa asigana automaticamente un numero de ID");

        jLabel1.setText("Limite credito");

        txtLimiteCredito.setToolTipText("Ingrese el limit de credito para este cliente");

        jLabel2.setText("Dias credito");

        jLabel3.setText("Tipo cliente ");

        txtTipoCliente.setEditable(false);
        txtTipoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoCliente.setText("A");

        cbxDiasCredito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "15", "30", "60", "90", "120" }));

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createSequentialGroup()
                            .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(lblTelCliente))
                                .addComponent(lblCelular))
                            .addGap(38, 38, 38))
                        .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                            .addComponent(lblIdCliente)
                            .addGap(34, 34, 34)))
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLimiteCredito)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPersona))
                    .addComponent(txtTelCliente)
                    .addComponent(txtCelular))
                .addGap(18, 18, 18)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblEmail)
                    .addComponent(lblDirCliente)
                    .addComponent(lblNitCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(txtNitPersona)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDirCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(cbxDiasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCliente)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdPersona)
                    .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblNitCliente)
                    .addComponent(txtNitPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelCliente)
                    .addComponent(lblDirCliente)
                    .addComponent(txtDirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbxDiasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setText("Buscar");

        txtBuscar.setToolTipText("Ingreseel nombre dle cliente a buscar");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBuscar)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir)
                        .addComponent(btnLimpiar)
                        .addComponent(btnModificar)
                        .addComponent(btnGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //VARIABLES GLOBALES
    AccesoExcepciones Mensaje = new AccesoExcepciones();
    AccesoPersona NuevaPersona = new AccesoPersona();
    AccesoCliente NuevoCliente = new AccesoCliente();
    ObjetosPersona Persona = new ObjetosPersona();
    ObjetosCliente Cliente = new ObjetosCliente();
    boolean cliente_encontrado = false;
    boolean persona_encontrada = false;

    private void limpiarCampos() {
        
        btnGuardar.setEnabled(true);
        
        txtIdCliente.setText("");
        txtIdPersona.setText("");
        txtNitPersona.setText("");
        txtNomPersona.setText("");
        txtTelCliente.setText("");
        txtDirCliente.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
        txtLimiteCredito.setText("");
        //txtDiasCredito.setText("");
        txtTipoCliente.setText("A");
        cbxDiasCredito.setSelectedIndex(0);
        
        cliente_encontrado = false;
        persona_encontrada = false;
    }

    private void mostrarRegistrosGuardados() {

        DefaultTableModel tabla = new DefaultTableModel();

        ArrayList<ObjetosCliente> listaClientes = new ArrayList();
        ArrayList<ObjetosPersona> listaPersonas = new ArrayList();

        //VERIFICAR ALGUN ERROR AL CARGAR LA INFORMACION DE LOS CLIENTES
        try {
            listaPersonas = NuevaPersona.seleccionarPersona();
            listaClientes = NuevoCliente.seleccionarCliente();
            System.out.println("SE CONSULTARON LOS DATOS DE PERSONA O DE CLIENTES");
        } catch (Error error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consultar la informacion -> " + error);
        }

        //MOSTRAR LA INFORMACION DE LOS CLIENTES EN LA TABLA DE LA VISTA
        if (listaClientes.isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "No existen datos almacenados de clientes");
        } else {
            tabla.addColumn("NIT");
            tabla.addColumn("Nombre");
            tabla.addColumn("Direccion");
            tabla.addColumn("Telefono");
            tabla.addColumn("Celular");
            tabla.addColumn("Email");
            tabla.addColumn("Limite de credito");
            tabla.addColumn("Dias de credito");
            tabla.addColumn("Tipo cliente");
            tabla.setRowCount(listaClientes.size());
            int cCliente = 0;

            for (ObjetosCliente xCliente : listaClientes) {
                for (ObjetosPersona xPersona : listaPersonas) {
                    if (xCliente.getId_persona() == xPersona.getId_persona()) {
                        tabla.setValueAt(xPersona.getNit_persona(), cCliente, 0);
                        tabla.setValueAt(xPersona.getNom_persona(), cCliente, 1);
                        tabla.setValueAt(xCliente.getDir_cliente(), cCliente, 2);
                        tabla.setValueAt(xCliente.getTel_cliente(), cCliente, 3);
                        tabla.setValueAt(xCliente.getCelular_cliente(), cCliente, 4);
                        tabla.setValueAt(xCliente.getEmail_cliente(), cCliente, 5);
                        tabla.setValueAt(xCliente.getLimite_credito(), cCliente, 6);
                        tabla.setValueAt(xCliente.getDias_de_credito(), cCliente, 7);
                        tabla.setValueAt(xCliente.getTipo_cliente(), cCliente, 8);
                        System.out.println("SE CONSULTO CON EXITO EL NIT: " + xPersona.getNit_persona());
                    }
                }
                cCliente++;
            }

            tblCliente.setModel(tabla);
        }
    }

    private int obtenerIdPersona(String pNit_persona) {

        int id_persona = 0;
        ArrayList<ObjetosPersona> BuscarPersona = new ArrayList();

        try {
            BuscarPersona = NuevaPersona.buscarPersona(pNit_persona);
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consulta el NIT del Cliente -> " + error);
        }

        if (BuscarPersona.isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "No existe esta Persona en la Base de Datos");
        } else {
            id_persona = BuscarPersona.get(0).getId_persona();
        }

        return id_persona;
    }

    private int obtenerIdCliente(String pNit_cliente) {

        ArrayList<ObjetosCliente> BuscarCliente = new ArrayList();
        int vId_persona = 0;
        int vId_cliente = 0;

        //BUSCAR EL ID DE LA PERSONA
        vId_persona = obtenerIdPersona(pNit_cliente);

        //CONSULTAR EL ID DE LA PERSONA EN CLIENTE
        try {
            BuscarCliente = NuevoCliente.buscarCliente(vId_persona);
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("informacion", "Ocurrio un error al consulta este numero de NIT -> " + error);
        }

        //EVALUAR EL RESULTADO DE LA BUSQUEDA
        if (BuscarCliente.isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Debe crear este cliente en la base de datos");
        } else {
            if (BuscarCliente.size() > 1) {
                System.out.println("EXISTEN " + BuscarCliente.size() + " CLIENTES CON ESTE NUMERO DE NIT");
                Mensaje.manipulacionExcepciones("critico", "Este numero de Nit esta repetido");
            } else {
                vId_cliente = BuscarCliente.get(0).getId_cliente();
            }
        }

        return vId_cliente;
    }

    private void buscarEnRegistrosGuardados() {

        String busqueda = txtBuscar.getText();

        if (busqueda != null) {
            DefaultTableModel tabla = new DefaultTableModel();
            ArrayList<ObjetosCliente> listaClientes = new ArrayList();
            ArrayList<ObjetosPersona> listaPersonas = new ArrayList();

            //VERIFICAR ALGUN ERROR AL CARGAR LA INFORMACION DE LOS CLIENTES
            try {
                listaClientes = NuevoCliente.seleccionarCliente();
                listaPersonas = NuevaPersona.seleccionarPersona();
                System.out.println("SE CONSULTARON LOS DATOS DE PERSONA Y DE CLIENTES");
            } catch (Error error) {
                Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consultar la informacion -> " + error);
            }

            //MOSTRAR LA INFORMACION DE LOS CLIENTES EN LA TABLA DE LA VISTA
            if (listaClientes.isEmpty()) {
                Mensaje.manipulacionExcepciones("critico", "No existen datos almacenados de clientes");
            } else {
                tabla.addColumn("NIT");
                tabla.addColumn("Nombre");
                tabla.addColumn("Direccion");
                tabla.addColumn("Telefono");
                tabla.addColumn("Celular");
                tabla.addColumn("Email");
                tabla.addColumn("Limite de credito");
                tabla.addColumn("Dias de credito");
                tabla.addColumn("Tipo cliente");

                int cCliente = 0;
                int contadorFilas = 1;

                // RECORRO TODA LA LISTA DE PERSONAS
                for (ObjetosPersona xPersona : listaPersonas) {

                    // COMPARA CADA ELEMENTO NIT Y NOMBRE DE LA LISTA PARA VER SI ALGUNO ES EL BUSCADO
                    if (xPersona.getNit_persona().indexOf(busqueda) >= 0
                            || xPersona.getNom_persona().toUpperCase().indexOf(busqueda.toUpperCase()) >= 0) {


                        // SI LA BUSQUEDA COINCIDE RECORRO LA LISTA DE CLIENTES 
                        // PARA OBTENER LA DIRECCION Y EL TELEFONO DE LA PERSONA
                        for (ObjetosCliente xCliente : listaClientes) {
                            if (xPersona.getId_persona() == xCliente.getId_persona()) {

                                // ESTABLECE EL TAMAÑO DE LA TABLA
                                tabla.setRowCount(contadorFilas);

                                tabla.setValueAt(xPersona.getNit_persona(), cCliente, 0);
                                tabla.setValueAt(xPersona.getNom_persona(), cCliente, 1);
                                tabla.setValueAt(xCliente.getDir_cliente(), cCliente, 2);
                                tabla.setValueAt(xCliente.getTel_cliente(), cCliente, 3);
                                tabla.setValueAt(xCliente.getCelular_cliente(), cCliente, 4);
                                tabla.setValueAt(xCliente.getEmail_cliente(), cCliente, 5);
                                tabla.setValueAt(xCliente.getLimite_credito(), cCliente, 6);
                                tabla.setValueAt(xCliente.getDias_de_credito(), cCliente, 7);
                                tabla.setValueAt(xCliente.getTipo_cliente(), cCliente, 8);

                                System.out.println("SE ENCONTRO EL REGISTRO BUSCADO: " + xPersona.getNit_persona());

                                cCliente++;
                                contadorFilas++;
                            }
                        }

                    }
                }
                tblCliente.setModel(tabla);
            }
        } else {
            // SI NO HAY CARACTER DE BUSQUEDA SE DESPLIEGAN TODOS LOS DATOS
            mostrarRegistrosGuardados();
        }

    }

    private void buscarCliente() {

        cliente_encontrado = false;
        persona_encontrada = false;

        ArrayList<ObjetosPersona> BuscarPersona = new ArrayList();
        ArrayList<ObjetosCliente> BuscarCliente = new ArrayList();

        try {
            BuscarPersona = NuevaPersona.buscarPersona(txtNitPersona.getText());
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un erro al buscar informacion sobre esta persona -> " + error);
        }

        if (BuscarPersona.isEmpty()) {
            persona_encontrada = false;
            cliente_encontrado = false;
        } else {
            persona_encontrada = true;
            txtIdPersona.setText(String.valueOf(BuscarPersona.get(0).getId_persona()));
            txtNomPersona.setText(BuscarPersona.get(0).getNom_persona());

            try {
                BuscarCliente = NuevoCliente.buscarCliente(BuscarPersona.get(0).getId_persona());
            } catch (Exception error) {
                Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al buscar a este Cliente -> " + error);
            }

        }

        if (BuscarCliente.isEmpty()) {
            cliente_encontrado = false;
        } else {
            cliente_encontrado = true;
            txtIdCliente.setText(String.valueOf(BuscarCliente.get(0).getId_cliente()));
            txtDirCliente.setText(BuscarCliente.get(0).getDir_cliente());
            txtTelCliente.setText(String.valueOf(BuscarCliente.get(0).getTel_cliente()));
        }
    }

    private boolean verificarDatosCliente() {

        boolean vDatosCorrectos = true;

        if (txtNitPersona.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de NIT");
            vDatosCorrectos = false;
        }

        if (txtNomPersona.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el Nombre del cliente");
            vDatosCorrectos = false;
        }

        if (txtTelCliente.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de Telefono");
            vDatosCorrectos = false;
        }
        if (txtDirCliente.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese la Direccion del cliente");
            vDatosCorrectos = false;
        }
        if(txtCelular.getText().isEmpty()){
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de celular");
        }
        
        return vDatosCorrectos;
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        boolean persona_guardada = false;

        if (verificarDatosCliente()) {
            Persona.setId_persona(0);
            Persona.setNit_persona(txtNitPersona.getText());
            Persona.setNom_persona(txtNomPersona.getText());

            Cliente.setId_cliente(0);
            Cliente.setId_persona(0);
            Cliente.setDir_cliente(txtDirCliente.getText());
            Cliente.setTel_cliente(Integer.parseInt(txtTelCliente.getText()));
            Cliente.setCelular_cliente(Integer.parseInt(txtCelular.getText()));
            Cliente.setEmail_cliente(txtEmail.getText());
            Cliente.setLimite_credito(Float.parseFloat(txtLimiteCredito.getText()));
            //Cliente.setDias_de_credito(Integer.parseInt(txtDiasCredito.getText()));
            Cliente.setDias_de_credito(Integer.parseInt(cbxDiasCredito.getSelectedItem().toString()));
            Cliente.setTipo_cliente(txtTipoCliente.getText());
        }

        if (persona_encontrada == false && cliente_encontrado == false) {

            try {
                NuevaPersona.insertarPersona(Persona);
                persona_guardada = true;
            } catch (Exception error) {
                persona_guardada = false;
                Mensaje.manipulacionExcepciones("critico", "Ocurrio un erro al guardar la persona -> " + error);
            }

            if (persona_guardada == true) {
                try {
                    Cliente.setId_persona(obtenerIdPersona(txtNitPersona.getText()));
                    NuevoCliente.insertarCliente(Cliente);
                    limpiarCampos();
                    mostrarRegistrosGuardados();
                    Mensaje.manipulacionExcepciones("informacion", "Datos guardados exitosamente");
                } catch (Exception error) {
                    Mensaje.manipulacionExcepciones("critico", "Ocurrio un erro al guardar los datos de este Cliente -> " + error);
                }
            }
        }

        //SI LA PERSONA EXITE PERO EL CLIENTE, NO SE INSERTA UNICAMENTE EL CLIENTE
        if (persona_encontrada == true && cliente_encontrado == false) {
            try {
                Cliente.setId_persona(obtenerIdPersona(txtNitPersona.getText()));
                NuevoCliente.insertarCliente(Cliente);
                limpiarCampos();
                mostrarRegistrosGuardados();
                Mensaje.manipulacionExcepciones("informacion", "Datsos guardados exitosamente");
            } catch (Exception error) {
                Mensaje.manipulacionExcepciones("critico", "Ocurrio un erro al guardar los datos de este Cliente -> " + error);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNitPersonaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitPersonaFocusLost
        //Esto se eliminó por la implementación de FEL
        /*Pattern patron = Pattern.compile("[0-9]*[-][0-9A-Z]");
        Matcher expresion = patron.matcher(txtNitPersona.getText());
        if(expresion.matches()) {
            buscarCliente();
        } else {
            Mensaje.manipulacionExcepciones("critico", "Este no. de NIT no es valido");
            txtNitPersona.requestFocus();
        }*/
        buscarCliente();
    }//GEN-LAST:event_txtNitPersonaFocusLost

    private void txtNomPersonaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomPersonaFocusGained

        if (txtNitPersona.getText().isEmpty()) {
            txtNitPersona.requestFocus();
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de NIT para este cliente");
        }
    }//GEN-LAST:event_txtNomPersonaFocusGained

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        Mensaje.manipulacionExcepciones("interrogante", "¿Esta seguro que desea salir?");
        if (Mensaje.valor == 0) {
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarEnRegistrosGuardados();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        //ACTUALIZAR LOS DATOS DE PERSONA
        Persona.setId_persona(Integer.parseInt(txtIdPersona.getText()));
        Persona.setNit_persona(txtNitPersona.getText());
        Persona.setNom_persona(txtNomPersona.getText());
       
        try {
            Mensaje.manipulacionExcepciones("informacion", NuevaPersona.actualizarPersona(Persona));
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al actualizar Persona -> " + error);
        }
        //ACTUALIZAR LOS DATOS DE CLIENTE
        Cliente.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
        Cliente.setId_persona(Persona.getId_persona());
        Cliente.setDir_cliente(txtDirCliente.getText());
        Cliente.setTel_cliente(Integer.parseInt(txtTelCliente.getText()));
        Cliente.setCelular_cliente(Integer.parseInt(txtCelular.getText()));
        Cliente.setEmail_cliente(txtEmail.getText());
        Cliente.setLimite_credito(Float.parseFloat(txtLimiteCredito.getText()));
        //Cliente.setDias_de_credito(Integer.parseInt(txtDiasCredito.getText()));
        Cliente.setDias_de_credito(Integer.parseInt(cbxDiasCredito.getSelectedItem().toString()));
        Cliente.setTipo_cliente(txtTipoCliente.getText());

        try {
            Mensaje.manipulacionExcepciones("informacion", NuevoCliente.actualizarCliente(Cliente));
            mostrarRegistrosGuardados();
            limpiarCampos();
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al actualizar el Cliente -> " + error);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        
        btnGuardar.setEnabled(false);
        if (String.valueOf(tblCliente.getSelectedColumn()).equals("0")) {
            int fila_seleccionada = tblCliente.getSelectedRow();
            int columna_seleccionada = tblCliente.getSelectedColumn();
            txtNitPersona.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada)));
            txtNomPersona.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 1)));
            txtDirCliente.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 2)));
            txtTelCliente.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 3)));
            txtCelular.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 4)));
            txtEmail.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 5)));
            txtLimiteCredito.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 6)));
            //txtDiasCredito.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 7)));
            cbxDiasCredito.setSelectedItem(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 7)));
            txtTipoCliente.setText(String.valueOf(tblCliente.getValueAt(fila_seleccionada, columna_seleccionada + 8)));
            
            // CON EL NUMERO DE NIT OBTENGO EL ID DE LA PERSONA
            txtIdPersona.setText(String.valueOf(obtenerIdPersona(txtNitPersona.getText())));
            
            //YA SELECCIONADO EL NIT BUSCO EL CLIENTE CON EL METODO BUSCAR ID CLIENTE
            txtIdCliente.setText(String.valueOf(obtenerIdCliente(txtNitPersona.getText())));
            
        }
    }//GEN-LAST:event_tblClienteMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbxDiasCredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblDirCliente;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdPersona;
    private javax.swing.JLabel lblNitCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTelCliente;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDirCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdPersona;
    private javax.swing.JTextField txtLimiteCredito;
    private javax.swing.JTextField txtNitPersona;
    private javax.swing.JTextField txtNomPersona;
    private javax.swing.JTextField txtTelCliente;
    private javax.swing.JTextField txtTipoCliente;
    // End of variables declaration//GEN-END:variables
}
